### ISSUE TITLE
Weird errors happening

### ISSUE THREAD

**Issue by remirr** [potmat/homebridge-google-nest-sdm#134] opened 2024-01-01 13:08 UTC
I have installed the plugin and got as fast as getting the video stream to show up in HomeKit from my Nest Gen 1 Doorbell which could still be used with a Nest account but I migrated to Google. 

The stream works but then after about 10 minutes it stops and never comes back. All I see is the nest logo and then in the plugin I get a huge string of errors. Anyone got any ideas?

![IMG_0158](https://github.com/potmat/homebridge-google-nest-sdm/assets/2309583/e682dd96-3b92-4e21-86b2-1b79af8a094f)

**Comment by potmat** [comment] 2024-01-01 15:42
As noted in the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq) the camera streams only last for a few minutes.  It's supposed to be possible to "extend" them but I haven't figured out how to make that work.

**Comment by remirr** [comment] 2024-01-01 22:54
So when I added the doorbell to HomeAssistant I was getting live streams all day long from the dashboard. I changed to Homebridge because my parents found HA to hard to use. So there must be a way to snapshot and stream as it works in Home Assistant

**Comment by tunju** [comment] 2024-01-06 07:29
I'm getting the same error code constantly as well as this one:
```
TypeError: Cannot read properties of undefined (reading 'mediaSessionId')
    at WebRtcNestStreamer.initialize (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/NestStreamer.ts:109:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraStreamingDelegate.startStream (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/StreamingDelegate.ts:300:20)
```

**Comment by potmat** [comment] 2024-02-18 19:52
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/136

**Closed by potmat** 2024-02-18 19:52 UTC
