### ISSUE TITLE
Thermostat Temperature Throttling

### ISSUE THREAD

**Issue by rudiv** [potmat/homebridge-google-nest-sdm#157] opened 2024-03-12 16:43 UTC
It seems with every increment of a temperature change this is hitting the API which in turn causes rate limits:

```
...
"errors":[{"message":"Rate limited for the SetThermostatTemperatureHeat command for the user.","domain":"global","reason":"rateLimitExceeded"}]}
Entryway Thermostat
```

Would be great if this could throttle the setting of this to the requested value by even 500ms or so to reduce the occurances of this.

**Comment by potmat** [comment] 2024-03-12 17:22
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/99

**Closed by potmat** 2024-03-12 17:22 UTC

**Comment by rudiv** [comment] 2024-03-12 17:24
Oops, my bad.
