### ISSUE TITLE
Ram bug

### ISSUE THREAD

**Issue by GillesWi** [potmat/homebridge-google-nest-sdm#170] opened 2024-05-23 20:08 UTC
[HDS ::ffff:192.168.0.228] Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.

Rpi 4b crashes after a few days because memory is filled up... could it be because of this? Only in the latest versions

**Comment by Abcmsaj** [comment] 2024-06-08 01:09
I’ve got this too. It’ll open a new instance of ffmpeg on my Mac every time this error occurs and so I’ve ended up having to kill 15-20 ffmpeg processes at once to free up memory

**Comment by ShadowRegent** [comment] 2024-06-15 17:16
I'm also having this issue and have many ffmpeg processes stuck running.

**Comment by potmat** [comment] 2024-10-01 17:39
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/150

**Closed as completed by potmat** 2024-10-01 17:39 UTC
