### ISSUE TITLE
Encountered unexpected error on generator Error

### ISSUE THREAD

**Issue by GillesWi** [potmat/homebridge-google-nest-sdm#167] opened 2024-04-20 16:49 UTC
I get recurring errors in the Homebridge logs that are seeming to take up a lot of Raspberry Pi resources. However the stream in the Apple Home app still works. What could be the cause of this? 

```
[20/04/2024, 18:45:47] [homebridge-google-nest-sdm] Encountered unexpected error on generator Error: Unexpected state!
    at HksvStreamer.generator (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/HksvStreamer.ts:141:19)
    at DoorbellStreamingDelegate.handleRecordingStreamRequest (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/StreamingDelegate.ts:559:24)
[HDS ::ffff:192.168.0.228] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[20/04/2024, 18:46:01] [homebridge-google-nest-sdm] Encountered unexpected error on generator Error: Unexpected state!
    at HksvStreamer.generator (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/HksvStreamer.ts:141:19)
    at DoorbellStreamingDelegate.handleRecordingStreamRequest (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/StreamingDelegate.ts:559:24)
[HDS ::ffff:192.168.0.228] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[20/04/2024, 18:47:40] [homebridge-google-nest-sdm] Could not execute event image GET request:  {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at settle (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Doorbell.getEventImage (/var/lib/homebridge/node_modules/homebridge-google-nest-sdm/src/sdm/Camera.ts:67:35)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Basic g.0.eyJraWQiOiIyMzhiNTUxZE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJuZXN0LXNlY3VyaXR5LWF1dGhwcm94eSIsInN1YiI6Im5lc3RfaWQ6bmVzdC1waG9lbml4LXByb2Q6NDExNTQ5OSIsInBvbCI6IjNwLW9hdXRoLXNjb3BlLUFQSV9TRE1fU0VSVklDRS1jbGllbnQtMzM0Njk4MzA5NzIwLXRyNjMxN2Nlcjd2c3BzaTJlOGIwYXVmNWl0b3B1N3Q2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZXhwIjoxNzEzNjMxNjg1fQ.Djpht4JudjbqR8wq0w9MZjKNAsLZS2hkaHbWRm2WaxmQdRj5MHQtWU1XRsWNLUk1D-bswI6te5fz-JBFW1xEDETBiavA6PZUU89dB_n4m6qGpxUFsxryP_-ZDYNEjB2-J35tvhv2G2tznWuvRfprCKqXG3I3Dkfn4Xy0SNcjEhf8f7dWem6ymKsau-WtRjJzQg_yc-i5lKSfSFHNSXceTxfWjsep3v-eHEX82J7_zMoTTxhDo4UaAzAfHVfG5ita96fm9n16QE0BWpKZnxeZzR47iJSP4JPHXGDEd2Vah_30NZD58A","User-Agent":"axios/1.6.7","Accept-Encoding":"gzip, compress, deflate, br"},"responseType":"text","responseEncoding":"base64","method":"get","url":"https://nexusapi-eu1.dropcam.com/sdm_resource/CiUA2vuxr5g_frCa4gOVUSpH34ALRIqpZ2eNmtqfgyEsABAIHtZ3EXhK7VcsaS-Ryf-0pQen_kbrwhDWWg9XZ-7NLDmAZq0Ph09QtWB_NXKQcJc2CpJIahb9pq_AnLLcC7vuDF1zj-P2dI_x4VsQ5dUvPIoz9IdBT7Hw6fReIMjEtRTOZdnxGTfTLu3kByhVbszqNN-1twvkhnK9qAgPEeWxHGTb2ucA6wZA3Px1zIeqc0s2K6LgwojsT3BoeJKmk4Gih1ZrBFHL3VnRGu5wfx8lOL_3SoZAMtUO/snapshot"},"code":"ERR_BAD_RESPONSE","status":500} Front Door Doorbell
```

**Comment by potmat** [comment] 2024-10-01 17:40
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/150

**Closed as completed by potmat** 2024-10-01 17:40 UTC
