### ISSUE TITLE
[Feature Request] Would like to have an eco-mode toggle

### ISSUE THREAD

**Issue by jpiccari** [potmat/homebridge-google-nest-sdm#154] opened 2024-03-06 04:28 UTC
The APIs offer an interface to manage the Nest Eco mode. Would be great if toggling heat/off was heat/eco/off or perhaps a config to set off to be eco mode instead of actually off. As a last resort, the other nest plugins expose eco mode as a light switch. I don't love this but something is better than nothing.

I'm willing to help on this but looking for some guidance on how the feature should behave and some pointers on the Apple HomeKit details for what may/may not be possible in terms of replicating the Nest UI.

**Comment by potmat** [comment] 2024-03-06 19:10
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/23#issuecomment-1149955989

**Closed by potmat** 2024-03-06 19:10 UTC
